apiVersion: v1 
kind: Pod 
metadata: 
  name: counter
spec: 
  containers:
  - name: counter1
    image: python:3.13.9-alpine3.21
    args: ['/bin/sh', '-c','while true;do echo $(date);sleep 1; done']

