version: '3'
services:
  mesin1:
    network_mode: 'host'
    privileged: true
    container_name: mesin1
    image: royyana/vmdev:2.00
    user: root
    environment:
      - "AUTH=user1:mesin1"
      - "PORTSSH=10022"
      - "PORTTTYD=10000"
      - "PATH=$PATH:/script"
      - "TMUXCMD=attach -t mysession"
    cap_add:
      - ALL
      - SYS_RAWIO
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/pts:/dev/pts"
      - "/dev/mem:/dev/mem"
      - "/dev/shm:/dev/shm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev/kvm:/dev/kvm
      - /dev/shm:/dev/shm
      - /dev/pts:/dev/pts
      - ./script:/script:rw
      - ./work:/home/work
    working_dir: /home/work
    entrypoint: /bin/sh /script/entrypoint.sh


